//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СartridgeMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartridges
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> printer_id { get; set; }
        public string number { get; set; }
        public string model { get; set; }
        public Nullable<int> state { get; set; }
    }
}
