//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СartridgeMaster
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<locations> locations { get; set; }
        public virtual DbSet<operations> operations { get; set; }
        public virtual DbSet<printers> printers { get; set; }
        public virtual DbSet<cartridges> cartridges { get; set; }
        public virtual DbSet<operation_types> operation_types { get; set; }
        public virtual DbSet<state_types> state_types { get; set; }
    }
}
