//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СartridgeMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class operations
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> object_id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> operation { get; set; }
        public string notes { get; set; }
    }
}
