//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СartridgeMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class operation_types
    {
        public System.Guid id { get; set; }
        public Nullable<int> object_type { get; set; }
        public Nullable<int> operation_value { get; set; }
        public string name { get; set; }
        public Nullable<System.Guid> state { get; set; }
    }
}
